name: MATH6380P
channels:
  - pytorch
  - conda-forge
  - anaconda-fusion
  - defaults
dependencies:
  - attrs=19.1.0
  - backcall=0.1.0
  - blas=1.0
  - bleach=3.1.0
  - ca-certificates=2019.9.11
  - certifi=2019.9.11
  - cffi=1.12.3
  - cycler=0.10.0
  - decorator=4.4.0
  - defusedxml=0.6.0
  - entrypoints=0.3
  - freetype=2.9.1
  - gettext=0.19.8.1
  - glib=2.56.2
  - icu=58.2
  - ipykernel=5.1.2
  - ipython=7.8.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.5.1
  - jedi=0.15.1
  - jinja2=2.10.1
  - joblib=0.13.2
  - jpeg=9b
  - json5=0.8.5
  - jsonschema=3.0.2
  - jupyter=1.0.0
  - jupyter_client=5.3.1
  - jupyter_console=6.0.0
  - jupyter_core=4.5.0
  - jupyterlab=1.1.4
  - jupyterlab_server=1.0.6
  - kiwisolver=1.1.0
  - libffi=3.2.1
  - libiconv=1.15
  - libpng=1.6.37
  - libsodium=1.0.16
  - libtiff=4.0.10
  - markupsafe=1.1.1
  - matplotlib=3.1.1
  - mistune=0.8.4
  - mkl=2019.4
  - mkl-service=2.3.0
  - mkl_fft=1.0.14
  - mkl_random=1.0.2
  - nbconvert=5.5.0
  - nbformat=4.4.0
  - ninja=1.9.0
  - notebook=6.0.1
  - numpy=1.16.5
  - numpy-base=1.16.5
  - olefile=0.46
  - openssl=1.1.1c
  - pandas=0.25.1
  - pandoc=2.2.3.2
  - pandocfilters=1.4.2
  - parso=0.5.1
  - patsy=0.5.1
  - pcre=8.43
  - pexpect=4.7.0
  - pickleshare=0.7.5
  - pillow=6.1.0
  - pip=19.2.2
  - prometheus_client=0.7.1
  - prompt_toolkit=2.0.9
  - ptyprocess=0.6.0
  - pycparser=2.19
  - pygments=2.4.2
  - pyparsing=2.4.2
  - pyqt=5.9.2
  - pyrsistent=0.14.11
  - python=3.7.4
  - python-dateutil=2.8.0
  - pytorch=1.2.0
  - pytz=2019.2
  - pyzmq=18.1.0
  - qt=5.9.7
  - qtconsole=4.5.5
  - scikit-learn=0.21.3
  - scipy=1.3.1
  - seaborn=0.9.0
  - send2trash=1.5.0
  - setuptools=41.0.1
  - sip=4.19.8
  - six=1.12.0
  - sqlite=3.29.0
  - statsmodels=0.10.1
  - terminado=0.8.2
  - testpath=0.4.2
  - tk=8.6.8
  - torchvision=0.4.0
  - tornado=6.0.3
  - traitlets=4.3.2
  - wcwidth=0.1.7
  - webencodings=0.5.1
  - wheel=0.33.4
  - widgetsnbextension=3.5.1
  - xz=5.2.4
  - zeromq=4.3.1
  - zlib=1.2.11
  - zstd=1.3.7
  - pip:
      - appdirs==1.4.3
      - configparser==4.0.2
      - kymatio==0.1.0